services:
  # Première application (player-app)
  player-application:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./player-app/:/usr/share/nginx/html/
      - ./assets/:/usr/share/nginx/html/assets/
      - ./components/:/usr/share/nginx/html/components/
      - ./data/:/usr/share/nginx/html/data/
      - ./pages/:/usr/share/nginx/html/pages/
      - ./src/:/usr/share/nginx/html/src/
      - ./env.js:/usr/share/nginx/html/env.js
